// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Tsuru",
            "url": "https://github.com/tsuru/acl-api"
        },
        "license": {
            "name": "BSD 3-Clause License",
            "url": "https://github.com/tsuru/acl-api/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apps/{app}/rules": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "List application rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "app",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/apps/{app}/sync": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Synchronize application rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "app",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SyncCountResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/jobs/{job}/rules": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List job rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job name",
                        "name": "job",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Create a service instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Creator",
                        "name": "user",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tsuru event ID",
                        "name": "eventid",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources/plans": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "List service plans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.EmptyResponse"
                            }
                        }
                    }
                }
            }
        },
        "/resources/{instance}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Get service instance information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.infoItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Update a service instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Delete a service instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources/{instance}/bind": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Bind a unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Unbind a unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/resources/{instance}/bind-app": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Bind an application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "app-name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Unbind an application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "app-name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources/{instance}/binds/jobs/{job}": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Bind a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job name",
                        "name": "job",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Unbind a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job name",
                        "name": "job",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources/{instance}/rule": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "List service instance rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.serviceRuleData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Add a service instance rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service rule",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ServiceRule"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Tsuru user",
                        "name": "X-Tsuru-User",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Tsuru event ID",
                        "name": "X-Tsuru-Eventid",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ServiceRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources/{instance}/rule/{rule}": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Remove a service instance rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "rule",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/resources/{instance}/status": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Get service instance status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/resources/{instance}/sync": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "Synchronize service instance rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance name",
                        "name": "instance",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/rules": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "List rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "RuleID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Rule name",
                        "name": "RuleName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Create a rule",
                "parameters": [
                    {
                        "description": "Rule",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Rule"
                        }
                    },
                    {
                        "type": "boolean",
                        "description": "Wait for synchronization before responding",
                        "name": "wait-sync",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Rule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/rules/sync": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "List rule synchronization data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.RuleSyncInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/rules/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Get a rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Rule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Delete a rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/rules/{id}/sync": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Get rule synchronization data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.RuleSyncInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Synchronize a rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
        "/services": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-resources"
                ],
                "summary": "List service instances",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request correlation ID",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ServiceInstance"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APIError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "api.EmptyResponse": {
            "type": "object"
        },
        "api.SyncCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "api.infoItem": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api.serviceRuleData": {
            "type": "object",
            "properties": {
                "ExpandedRules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Rule"
                    }
                },
                "RulesSync": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.RuleSyncInfo"
                    }
                },
                "ServiceInstance": {
                    "$ref": "#/definitions/types.ServiceInstance"
                }
            }
        },
        "types.ExternalDNSRule": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ProtoPort"
                    }
                },
                "SyncWholeNetwork": {
                    "type": "boolean"
                }
            }
        },
        "types.ExternalIPRule": {
            "type": "object",
            "properties": {
                "IP": {
                    "type": "string"
                },
                "Ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ProtoPort"
                    }
                },
                "SyncWholeNetwork": {
                    "type": "boolean"
                }
            }
        },
        "types.KubernetesServiceRule": {
            "type": "object",
            "properties": {
                "ClusterName": {
                    "type": "string"
                },
                "Namespace": {
                    "type": "string"
                },
                "ServiceName": {
                    "type": "string"
                }
            }
        },
        "types.ProtoPort": {
            "type": "object",
            "properties": {
                "Port": {
                    "type": "integer",
                    "format": "int32"
                },
                "Protocol": {
                    "type": "string"
                }
            }
        },
        "types.RpaasInstanceRule": {
            "type": "object",
            "properties": {
                "Instance": {
                    "type": "string"
                },
                "ServiceName": {
                    "type": "string"
                }
            }
        },
        "types.Rule": {
            "type": "object",
            "properties": {
                "Created": {
                    "type": "string"
                },
                "Creator": {
                    "type": "string"
                },
                "Destination": {
                    "$ref": "#/definitions/types.RuleType"
                },
                "Metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "Removed": {
                    "type": "boolean"
                },
                "RuleID": {
                    "type": "string"
                },
                "RuleName": {
                    "type": "string"
                },
                "Source": {
                    "$ref": "#/definitions/types.RuleType"
                }
            }
        },
        "types.RuleSyncData": {
            "type": "object",
            "properties": {
                "EndTime": {
                    "type": "string"
                },
                "Error": {
                    "type": "string"
                },
                "Removed": {
                    "type": "boolean"
                },
                "StartTime": {
                    "type": "string"
                },
                "Successful": {
                    "type": "boolean"
                },
                "SyncResult": {
                    "type": "string"
                }
            }
        },
        "types.RuleSyncInfo": {
            "type": "object",
            "properties": {
                "EndTime": {
                    "type": "string"
                },
                "Engine": {
                    "type": "string"
                },
                "PingTime": {
                    "type": "string"
                },
                "RuleID": {
                    "type": "string"
                },
                "Running": {
                    "type": "boolean"
                },
                "StartTime": {
                    "type": "string"
                },
                "SyncID": {
                    "type": "string"
                },
                "Syncs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.RuleSyncData"
                    }
                }
            }
        },
        "types.RuleType": {
            "type": "object",
            "properties": {
                "ExternalDNS": {
                    "$ref": "#/definitions/types.ExternalDNSRule"
                },
                "ExternalIP": {
                    "$ref": "#/definitions/types.ExternalIPRule"
                },
                "KubernetesService": {
                    "$ref": "#/definitions/types.KubernetesServiceRule"
                },
                "RpaasInstance": {
                    "$ref": "#/definitions/types.RpaasInstanceRule"
                },
                "TsuruApp": {
                    "$ref": "#/definitions/types.TsuruAppRule"
                },
                "TsuruJob": {
                    "$ref": "#/definitions/types.TsuruJobRule"
                }
            }
        },
        "types.ServiceInstance": {
            "type": "object",
            "properties": {
                "BaseRules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ServiceRule"
                    }
                },
                "BindApps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "BindJobs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Creator": {
                    "type": "string"
                },
                "EventID": {
                    "type": "string"
                },
                "InstanceName": {
                    "type": "string"
                }
            }
        },
        "types.ServiceRule": {
            "type": "object",
            "properties": {
                "Created": {
                    "type": "string"
                },
                "Creator": {
                    "type": "string"
                },
                "Destination": {
                    "$ref": "#/definitions/types.RuleType"
                },
                "EventID": {
                    "type": "string"
                },
                "Metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "Removed": {
                    "type": "boolean"
                },
                "RuleID": {
                    "type": "string"
                },
                "RuleName": {
                    "type": "string"
                },
                "Source": {
                    "$ref": "#/definitions/types.RuleType"
                }
            }
        },
        "types.TsuruAppRule": {
            "type": "object",
            "properties": {
                "AppName": {
                    "type": "string"
                },
                "PoolName": {
                    "type": "string"
                }
            }
        },
        "types.TsuruJobRule": {
            "type": "object",
            "properties": {
                "JobName": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "Set when compiling",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ACL API",
	Description:      "ACL API stores network access rules consumed by acl-operator.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
